FROM openjdk:17.0.1-jdk-slim

RUN apt-get update && \
    apt-get install -y software-properties-common && \
    apt-get install -y python3-pip
EXPOSE 8080
# install wget
RUN apt-get -y update
RUN apt-get -y install wget apt-utils gnupg

# Cleanup
RUN apt-get -y autoremove && \
    apt-get clean

ENV PYTHONUNBUFFERED True
WORKDIR /app
COPY *.txt .
RUN pip install --no-cache-dir --upgrade pip -r requirements.txt
COPY . ./

CMD ["python3", "tg_input.py"]